"""Revision

Revision ID: bec3a65925a5
Revises: 0109865b6261
Create Date: 2025-02-12 02:03:24.459800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'bec3a65925a5'
down_revision: Union[str, None] = '0109865b6261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Items', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=256),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Items', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=256),
               existing_nullable=True)
    # ### end Alembic commands ###
